### PR TITLE
database decryption

### PR DESCRIPTION
**Pull request by NKWBTB**
Add a script to rescue the data from the encrypted Mendeley database

### CODE REVIEW

**Comment by forrestbao** [comment]
Good and prompt progress. 

1. Why separating these two arguments? 
`--path /path/to/bin/mendeleydesktop --database <some_id>@www.mendeley.com.sqlite` Why not just one argument that goes all the way to the SQLite file? 

2. I just got the chance to look into the method and ref link. This rescue will alternate the SQLite file that Mendeley uses. So could you please modify and expand your script such that it will save the decrypted database to a different SQLite file? Just let your script create a copy of the file, and work on the copy. Also, add a new argument to specify the write-to filename, with default value as `{input_sql_file}.sql.bak`.

**Comment by NKWBTB** [comment]
> 
> 
> Good and prompt progress.
> 
>     1. Why separating these two arguments?
>        `--path /path/to/bin/mendeleydesktop --database <some_id>@www.mendeley.com.sqlite` Why not just one argument that goes all the way to the SQLite file?

What the script does is to leverage the debug mode of the mendeleydesktop, so we need the file path of the main program. We also need the filename of the database to locate the critical breakpoint.

> 
>     2. I just got the chance to look into the method and ref link. This rescue will alternate the SQLite file that Mendeley uses. So could you please modify and expand your script such that it will save the decrypted database to a different SQLite file? Just let your script create a copy of the file, and work on the copy. Also, add a new argument to specify the write-to filename, with default value as `{input_sql_file}.sql.bak`.

I can work on a shell script to backup the database file first and restore the database after the rescue process.

**Comment by forrestbao** [comment]
>>     2. I just got the chance to look into the method and ref link. This rescue will alternate the SQLite file that Mendeley uses. So could you please modify and expand your script such that it will save the decrypted database to a different SQLite file? Just let your script create a copy of the file, and work on the copy. Also, add a new argument to specify the write-to filename, with default value as `{input_sql_file}.sql.bak`.

> I can work on a shell script to backup the database file first and restore the database after the rescue process.

Please do it in Python. One Python script for everything. Thanks.

**Comment by NKWBTB** [comment]
> > > ```
> > > 2. I just got the chance to look into the method and ref link. This rescue will alternate the SQLite file that Mendeley uses. So could you please modify and expand your script such that it will save the decrypted database to a different SQLite file? Just let your script create a copy of the file, and work on the copy. Also, add a new argument to specify the write-to filename, with default value as `{input_sql_file}.sql.bak`.
> > > ```
> 
> > I can work on a shell script to backup the database file first and restore the database after the rescue process.
> 
> Please do it in Python. One Python script for everything. Thanks.

OK, I added a new argument to specify the save file, also added the backup procedure in the script.

**Comment by forrestbao** [comment]
It seems that I didn't make myself very clear. This is the workflow I want: 
1. Copy the encrypted DB to a new DB file specified at `save` or default path/name
2. Perform everything on the new DB file -- read and write is only on the new DB file so the encrypted DB file is not touched. 

Your code implements what [the post](https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db) that I shared with you does. But apparently it is more redundant than what I suggested above, and it won't work if you don't have write privilege to the original DB file. And the author didn't do [preserving copy](https://superuser.com/questions/114195/how-to-copy-a-file-in-unix-without-altering-its-last-modified-time/114198).

**Comment by NKWBTB** [comment]
> 
> It seems that I didn't make myself very clear. This is the workflow [1] I suggested:
> 
>     1. Copy the encrypted DB to a new DB file specified at `save` or default path/name
> 
>     2. Perform everything on the new DB file -- read and write only the new DB file so the encrypted DB file is never touched.
> 
> Please modify your code accordingly.
> 
> Note [1] Your code implements what [the post](https://eighty-twenty.org/2018/06/13/mendeley-encrypted-db) that I shared with you does. But apparently it is more redundant than what I suggested above, and it won't work if you don't have write privilege to the original DB file. And the author didn't do [preserving copy](https://superuser.com/questions/114195/how-to-copy-a-file-in-unix-without-altering-its-last-modified-time/114198).

Sorry, I may have not explained how the script works clearly. The script does not decide which DB file to load, it simply waits for the mendeleydesktop to trigger the breakpoint when loading the DB file. The argument in the script for the DB file is to determine if the application loaded the correct DB file we wanted. So only mendeleydesktop the application itself knows which DB file to load, which means the application should have the write privilege to the file and the process shall only work on the original DB file. Although we may have a way to find out the logic how the program knows which DB file to load, it requires a deep digging into the source code and takes a long time.

A simpler way I think is to fix the code to do the preserve copying during backup and restoration.

> And for god sake, please
> 
> * no global variables -- so the `attempt` function can be imported elsewhere to use.
> 
> * use `if __name__ == "__main__"` -- so the library can be imported elsewhere to use.

I will correct it in the upcoming commit.

**Comment by forrestbao** [comment]
@NKWBTB Please fix the code in the workflow I specified. Thanks.

**Comment by NKWBTB** [comment]
> 
> 
> @NKWBTB Please fix the code in the workflow I specified. Thanks.

Workflow fixed.

**Pull request merged**
